name: Release via GitHub Tag (with dev versions)

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          cargo install cargo-release --locked
          pip install maturin tomlkit semver

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF_NAME}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Set release version
        run: |
          VERSION=${{ steps.version.outputs.version }}
          echo "Setting release version $VERSION"
          cargo set-version $VERSION
          python - <<'PYCODE'
          import tomlkit
          from pathlib import Path
          path = Path("pyproject.toml")
          data = tomlkit.parse(path.read_text())
          data["project"]["version"] = "${{ steps.version.outputs.version }}"
          path.write_text(tomlkit.dumps(data))
          PYCODE

      - name: Commit release version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml pyproject.toml
          git commit -m "chore: set release version v${{ steps.version.outputs.version }}"
          git push origin HEAD:main
