name: Release via GitHub Tag (with dev versions)

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install tools
        run: |
          cargo install cargo-set-version

      - name: Detect current branch
        id: branch
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            BRANCH="${GITHUB_HEAD_REF}"
          else
            # For releases or tags
            BRANCH="${GITHUB_REF_NAME}"
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "Detected branch: $BRANCH"
          BRANCH=$(git branch --show-current)
          BRANCH="${{ github.event.release.target_commitish }}"
          echo "Detected branch: $BRANCH"

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF_NAME}
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Set release version
        run: |
          VERSION=${{ steps.version.outputs.version }}
          echo "Setting release version $VERSION"
          cargo set-version $VERSION

      - name: Commit release version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "chore: set release version v${{ steps.version.outputs.version }}"
          git push origin HEAD:$BRANCH
